### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by ilyar** [CultOfOpenSource/bem-bootstrap#25]
```
rm -f test && mkdir test && cd $_
git clone git@github.com:CultOfOpenSource/bem-bootstrap.git
cd bem-bootstrap
npm i
npm start

> bem-bootstrap@4.0.0-beta start /home/ilyar/prj/test/bem-bootstrap
> enb server

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bem-bootstrap@4.0.0-beta start: `enb server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bem-bootstrap@4.0.0-beta start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ilyar/.npm/_logs/2017-12-16T19_51_23_317Z-debug.log

```

**Comment by ilyar** [comment]
Ошибка означает, что сервер уже запущен или другой процесс занял порт, как вариант решения `env server --port 8181` запустить на другом порте или убедится что это не повторная попытка запустить сервер.
